---
title: Project Review Template 
author: "Pooja Gokhale"
date: 04/23/2025
format: 
  html:
    toc: true
    toc-depth: 3
    number-sections: true
---

# Overview

Title of project: Immune-Related Adverse Events (irAEs) Associated with Immune Checkpoint Inhibitor (ICI) Therapy in Bladder Cancer: An Analysis of the FDA Adverse Event Reporting System (FAERS)

Name of project author(s):

Name of project reviewer:Doreen_Kibuule_Kalembe


# Instructions

Write your comments and feedback below for each section/component of the project. The goal should be to help the author improve their project. Make comments as constructive and actionable as possible. You can provide both criticism and praise.

For each component, pick one summary statement by deleting the ones that do not apply and keeping only the one that you think most closely summarizes a given component. 

Make sure your final document compiles/renders into a readable, well-formatted html document.

Delete any sections/text of this template that are not part of your final review document. (Including these instructions.)


# Specific project content evaluation
Evaluate the different parts of the project by filling in the sections below.


## Background, Context and Motivation

How well is the context of the project described? Is a comprehensive background, including summary of previous/related work given? Is the project well placed into the context of existing work (including proper referencing of existing work). Is it clear why the project was undertaken and what new information it hopes to provide?

### Feedback and Comments

The author described the project well. The background was well written with a series of previous work and it was cleary highlighted why they decided to take on this question.

### Summary assessment (PICK ONE, DELETE THE OTHERS)

* strong contextualization and motivation


## Question description
How well and clear are the question(s)/hypotheses the project aims to address described? Is it clear how the questions relate to the data?


### Feedback and Comments

The question was  is clearly defined in the background clearly stating the project. 

### Summary assessment

* question/hypotheses was well explained



## Data description
How well is the data overall described? Is the source provided? Is a codebook or other meta-information available that makes it clear what the data is? 

### Feedback and Comments

The data source was clearly stated and the all concerns regarding the data set was well explained.

### Summary assessment

* source and overall structure of data well explained


## Data wrangling and exploratory analysis
How well is the data cleaned/processed and explored? Are all steps reasonable and well explained? Are alternatives discussed and considered? Are meaningful exploratory results shown (e.g. in the supplementary materials)?

### Feedback and Comments

The data exploratory analysis was well done and and meaningful results were provided by the author

### Summary assessment

* essentially no weaknesses in wrangling and exploratory component



## Appropriateness of Analysis
Were the analysis methods appropriate for the data? Was the analysis done properly? Were different components of the analysis (e.g. performance measure, variable selection, data pre-processing, model evaluation) done in the best way possible and explained well?

### Feedback and Comments

The analyisis was clearly done and well explained for the data that was given. All parts of data wrangling and cleaning were clearly done and each step was well explained.

### Summary assessment

* strong and reasonable analysis

## Presentation
How well are results presented? Are tables and figures easy to read and understand? Are the main figures/tables publication level quality? 

### Feedback and Comments

The results were well presented with figures and tables easy to read and understand. All the figures and tables were publication quality.

### Summary assessment

* results are very well presented


## Discussion/Conclusions
Are the study findings properly discussed? Are strengths and limitations acknowledged? Are findings interpreted properly?

### Feedback and Comments
The limitation of the study were clearly stated by the author and the strength were well highlighted. However the findings were not clearly discussed. Either it was short since i had a hard time understanding what your results mean. Maybe i needed to read the manuscript again but it would be better if you improved alittle bit on the discussion

### Summary assessment

*Well formulated and conclusion too.



## Further comments

The project was well scripted and well referenced. You have done well in the data exploration and analysis. Well done Pooja



# Overall project content evaluation
Evaluate overall features of the project  by filling in the sections below.


## Structure
Is the project well structured? Are files in well labeled folders? Do files have reasonable names? Are all "junk" files not needed for analysis/reproduction removed? By just looking at files and folders, can you get an idea of how things fit together?

### Feedback and Comments

The project is mostly well structured. 

### Summary assessment

* well structured


## Documentation 
How well is the project documented? Are you able to understand each step of the whole analysis, each decision that was made, and each line of code? Is enough information provided as comments in code or as part of Rmd files? 

### Feedback and Comments

The project was well documented and providing everything needed for reproduciblility.
Enough comment were given to each line of code and i was able to follow through with what the author was doing.

### Summary assessment

* fully and well documented



## Reproducibility
Are all results fully reproducible? Is documentation provided which clearly explains how to reproduce things, and does it work without the need for any manual intervention? Are you able to re-run the whole analysis without having to do manual interventions/edits?

### Feedback and Comments

All the codes are clearly provided  for reproduciblity. Project was well documented and i was able to rerun the whole analysis without having to do any edits.


### Summary assessment

* fully reproducible without issues


## Thoroughness
How thorough was the overall study? Were alternatives (e.g. different ways of processing the data or different models) considered? Were alternatives discussed? Were the questions/hypotheses fully and thoroughly addressed?

### Feedback and Comments

The overall study was interesting to follow through. Not many alternatives were discussed but guidelines for future research were given

### Summary assessment

* strong level of thorougness


## Further comments

Well done Pooja. Apart from the needing to add in more information about your discussion, I think your project was well scripted and I wish you the very best.





